project_id = "zixdilsnjchnyreybyqu"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.ai-chat]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = false