// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zixdilsnjchnyreybyqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppeGRpbHNuamNobnlyZXlieXF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDgyNjgsImV4cCI6MjA2Nzg4NDI2OH0.Oz8H7WycOO_5iAUaTH8nUxr7PQgU4QJYIc3pOGi8NoY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});